name: Build and Delpoy Code

on: [push, pull_request]

jobs:
  job1:
    env:
      FASTAPI_DB_URL: postgresql://${{secrets.DB_USERNAME}}:${{secrets.DB_PASSWORD}}@${{secrets.DB_HOSTNAME}}:5432/${{secrets.DB_NAME}}
      FASTAPI_SECRET_KEY: ${{ secrets.FASTAPI_SECRET_KEY}}
      FASTAPI_ALGORITHM: ${{ secrets.FASTAPI_ALGORITHM}}
      FASTAPI_TOKEN_EXPIRE_MINUTES: ${{ secrets.FASTAPI_TOKEN_EXPIRE_MINUTES}}
      DB_USERNAME: ${{ secrets.DB_USERNAME}}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
      DB_HOSTNAME: ${{ secrets.DB_HOSTNAME}}
      DB_PORT: 5432
      DB_NAME: ${{ secrets.DB_NAME}}

    services:
      postgres: 
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD}}
          POSTGRES_DB: ${{ secrets.DB_NAME}}_test
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: install python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest